services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: my_database
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  api:
    image: my-api-image:latest
    ports:
      - "5000:5000"
    depends_on:
      - db

  web:
    image: my-web-app:latest
    ports:
      - "8000:8000"
    depends_on:
      - api

volumes:
  db-data:
